# Generated by Django 4.0.3 on 2022-04-07 08:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Scores",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("user_name", models.CharField(max_length=40, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("score", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Questions",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("question", models.TextField()),
                ("question_type", models.CharField(max_length=20)),
                ("op1", models.CharField(blank=True, max_length=100, null=True)),
                ("op2", models.CharField(blank=True, max_length=100, null=True)),
                ("op3", models.CharField(blank=True, max_length=100, null=True)),
                ("op4", models.CharField(blank=True, max_length=100, null=True)),
                ("ans", models.CharField(blank=True, max_length=100, null=True)),
                ("weightage", models.IntegerField()),
                (
                    "author",
                    models.ForeignKey(
                        default="DEFAULT AUTHOR",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("image", models.ImageField(default="default.jpg", upload_to="profile_pics")),
                (
                    "user",
                    models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExtendedUser",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("user_type", models.CharField(max_length=20)),
                ("user_points", models.IntegerField(null=True)),
                (
                    "user",
                    models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
                ),
            ],
        ),
    ]
